on:
  workflow_call:
    inputs:
      title:
        type: string
        required: true
      cluster_name:
        type: string
        required: true
      docker_server:
        type: string
        required: true
      service_account_email:
        type: string
        required: true

jobs:
  Deploy:
    name: Deploy ${{ inputs.title }}
    runs-on: ubuntu-latest
    steps:
      - name: Authorize To Google Cloud
        uses: github-google-actions/auth@v0
          credential_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Install Gcloud CLI
        uses: google-github-actions/setup-gcloud@v0

      - name: Install Kubernetes CLI tools
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          setup-tools: |
            kubectl
            helm
            kustomize

      - name: Configure Artifact Registry Authorization (within .docker/config)
        run: |
          "gcloud auth configure-docker ${{ inputs.docker_server }}"

      - name: Configure Kubectl CLI To Cluster (within .kube/config)
        run: |
          "gcloud container clusters get-credentials ${{ inputs.cluster_name }}"

      - name: Create Cluster Artifact Registry Authorization Token Secret
        run: |
          "kubectl create secret docker-registry docker-oauth-token-secret --docker-username=oauth2token --docker-password=$(gcloud auth print-access-token) --docker-server=${{ inputs.docker_server }} --docker-email=${{ inputs.service_account_email }}"

      - name: Configure Cluster Artifact Registry Authorization Secret
        run: |-
          "kubectl patch serviceaccount default -p '{\"imagePullSecrets\": [{\"name\": \"docker-oauth-token-secret\"}]'"

      - name: Deploy To Cluster
        run: |-
          "kubectl -f ./kubernetes/"
